version: "3"
services:
    web:
        container_name: iudx-differential-privacy-arx-c
        image: iudx-differential-privacy-arx-i
        build: .
        ports:
          - "8070:8070"
        volumes:
            - .:/app

